[package]
name = "glyph-dispatch"
version = "0.1.0"
edition = "2024"

[dependencies]
operator-plugin={path="../plugins/operator-plugin"}
thiserror = "2.0.11"
tokio = { version = "1.43.0", features = ["sync", "rt-multi-thread"] }
